### ISSUE TITLE
Unable to resolve action, repository or version not found (`ETIMEDOUT`)

### ISSUE THREAD

**Issue by MetRonnie** [github/vscode-github-actions#143]
**Describe the bug**
Hovering over an action name fails to load any info about it from the GitHub API, and after a while I might get an error notification.

**To Reproduce**
See description above & screenshot below

**Expected behavior**
No error

**Screenshots**

![image](https://github.com/github/vscode-github-actions/assets/61982285/a8184468-1ee5-4635-b642-c13361cce1c6)

**Extension Version**
`v0.25.6`

OS: Linux & Windows

**Additional context**
From the logs for GitHub Actions Language Server:

```
[Error - 10:48:06 AM] Failed to fetch action metadata for actions/checkout/v3: 'request to https://api.github.com/repos/actions/checkout/contents/action.yml?ref=v3 failed, reason: connect ETIMEDOUT <some_ip_address>:443'
```

and
```
Failure to retrieve username:  Ms [HttpError]: request to https://api.github.com/user failed, reason: connect ETIMEDOUT <some_ip_address>:443
    at ~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2785024
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2856983
    at async wa.get (~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2866891)
    at async ~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2856918
    at async la (~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2856885)
    at async ~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2860689
    at async Object.getContext (~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2860645)
    at async oi (~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2733949)
    at async gn (~/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/server-node.js:2:2759192) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/user',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'VS Code GitHub Actions (0.25.4) octokit-rest.js/19.0.7 octokit-core.js/4.1.0 Node.js/16.14.2 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound e] }
  }
```

**Comment by bmainard** [comment]
Hello !
I have exactly the same problem. I'm on MacOS 13.3.1 and behind a proxy (configured in VSCode).
The extension's GUI is OK (you can clearly see the workflows of my repo) but the api calls made to github.com in the background when editing a workflow file are in timeout.

When I test that out of proxy, everything is OK.

<img width="1710" alt="image" src="https://github.com/github/vscode-github-actions/assets/56641524/a1f5b351-4234-4188-b655-bc2832ec15e8">

The discussion at #127 seems to reject a proxy problem but I think it is the cause.

**Comment by jimbrig** [comment]
Similar issue here, but only for certain actions

**Comment by tsela** [comment]
I have the exact same issue, but in my case the given error is ECONNRESET rather than ETIMEDOUT. Otherwise identical issue.

**Comment by michaelsoriano** [comment]
same issue here.

**Comment by cmanage1** [comment]
same issue with `serverless/github-action@v3.2`

**Comment by tvanantwerp** [comment]
Any updates on this issue?

Every single action I try to use has this error, and it's been ongoing for months.

<img width="684" alt="image" src="https://github.com/github/vscode-github-actions/assets/2487968/a0f45ae2-c5a5-4687-8ef1-5d07ccae8e1e">

<img width="185" alt="image" src="https://github.com/github/vscode-github-actions/assets/2487968/c62742ab-74f6-4958-90e0-48e2433cd8aa">

**Comment by AMD-NICK** [comment]
Re-authorization in VSCode helped me solve the problem

![screenshot_2023-11-15_23 09 25@2x](https://github.com/github/vscode-github-actions/assets/9200174/1e57888b-a0c3-4e8e-8a7d-bc8ff75b7b87)

**Comment by elasticdotventures** [comment]
This extension shouuld detect that the authorization is no longer valid and attempt to renew/refresh the github token. 

For others, if you want to confirm this is your issue - In vscode you can go to the OUTPUT then select "Github Actions" and you'll see messages about how authentication has failed.  

I have quite a few plugins which use github tokens and so it's possible this problem is related to interaction between them.

**Comment by yeasir01** [comment]
> Re-authorization in VSCode helped me solve the problem
> 
> ![screenshot_2023-11-15_23 09 25@2x](https://private-user-images.githubusercontent.com/9200174/283248298-1e57888b-a0c3-4e8e-8a7d-bc8ff75b7b87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzMyMTEsIm5iZiI6MTcwNjQzMjkxMSwicGF0aCI6Ii85MjAwMTc0LzI4MzI0ODI5OC0xZTU3ODg4Yi1hMGMzLTRlOGUtOGE3ZC1iYzhmZjc1YjdiODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDkwODMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDliNTZkMjkxNzVlN2MwNDc3NjYwYjgyMjFlMzBkY2ZlZWI1MDRlNmYwZWI3YmU5YjJmNDVmYWNkOTVhZThkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g0v1Onh55BBs9enEgnOmYmeKxA9SOcrHD7KWxIYIMOQ)

This seems to fix it. It seems like a bug that needs to be investigated.

**Comment by phenix3443** [comment]
same issues. look forward to resolve.

**Comment by ps29** [comment]
> Re-authorization in VSCode helped me solve the problem
> 
> ![screenshot_2023-11-15_23 09 25@2x](https://private-user-images.githubusercontent.com/9200174/283248298-1e57888b-a0c3-4e8e-8a7d-bc8ff75b7b87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjczNzgsIm5iZiI6MTcxMDIyNzA3OCwicGF0aCI6Ii85MjAwMTc0LzI4MzI0ODI5OC0xZTU3ODg4Yi1hMGMzLTRlOGUtOGE3ZC1iYzhmZjc1YjdiODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDcwNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmI5ZWZjMzg5Zjg0MDk3MWVkODk1M2YxMmIwYzlhMzY3YmI2YjRmMGY0ZjJhMDAwZmE5OTQ4YzlhNTBjZGYwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1ScLt7fBPZ9eXUmRLQ4BY7omUDKxs7YPWlMoRuCMvZs)

This helped me.😊

**Comment by foux** [comment]
Signing out and back in didn't sove it for me :/ 
Have the issue on `actions/checkout@v3` and `subosito/flutter-action@v2`

**Comment by eminizer** [comment]
Same problem for me, ongoing for actual years at this point, and signing out/back in does not resolve it. Uninstalling this extension, I fear.

**Comment by LenaPD** [comment]
Removing Cline extension fixed the problem for me for some reason. Signing in and out did not help.
