### ISSUE TITLE
ooo:  Request textDocument/completion failed with message: Maximum call stack size exceeded: Error: Request textDocument/completion failed with message: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ssbarnea** [github/vscode-github-actions#367]
**Describe the bug**

Extension is running out of memory sometimes:

```
2024-07-31 13:08:28.569 [error] Request textDocument/completion failed with message: Maximum call stack size exceeded: Error: Request textDocument/completion failed with message: Maximum call stack size exceeded
	at /Users/ssbarnea/.vscode/extensions/github.vscode-github-actions-0.26.3/dist/extension-node.js:2:633457
	at /Users/ssbarnea/.vscode/extensions/github.vscode-github-actions-0.26.3/dist/extension-node.js:2:633751
	at Timeout._onTimeout (/Users/ssbarnea/.vscode/extensions/github.vscode-github-actions-0.26.3/dist/extension-node.js:2:634113)
	at listOnTimeout (node:internal/timers:573:17)
	at process.processTimers (node:internal/timers:514:7)
2024-08-01 13:33:57.033 [error] [Extension Host] Error loading yaml file
```

**To Reproduce**
1. With this workflow '...'
2. Do this '...'
3. See error

**Expected behavior**

**Screenshots**

**Extension Version**
`v0.26.3`

**Additional context**

That is on a 64GB M1 max laptop, so bit unexpected. I wonder if that is caused by node running out of memory as I encountered recently another issue with it that required me to add `NODE_OPTIONS=--max-old-space-size=4096` in order to just run `yarn webpack`... :p

**Comment by DetachHead** [comment]
repro:

```yaml
jobs:
    asdf:
      strategy:
        matrix:
          python_version: ["3"]
```
place the cursor after the `3` and add a `.`:

![](https://github.com/user-attachments/assets/36314039-8bad-4e7e-ac68-a365098889d6)


i doubt this is memory related, its probably a recursive function call that's getting caught in an infinite loop

**Comment by ksg-dev** [comment]
+1

**Comment by frederikheld** [comment]
Can confirm @DetachHead's reproduction

**Comment by jsoref** [comment]
Recurs with 0.28.2.
