### ISSUE TITLE
Failure to retrieve username:  Ls [HttpError]: fetch failed

### ISSUE THREAD

**Issue by DrStrangepork** [github/vscode-github-actions#403]
**Describe the bug**
When I am editing a workflow file, and my mouse moves, I get an error box pup up repeatedly. It can pop up several times over the course of a single pointer movement down the file. 

**To Reproduce**
1. Edit any workflow file
2. Hover over any any of several steps/components of the workflow
3. See error

![image](https://github.com/user-attachments/assets/8b4c8df4-9a8a-450b-9e2c-7ab7eb5cb4ff)

When the popup occurs, I get this in the OUTPUT tab:

```
Failure to retrieve username:  Ls [HttpError]: fetch failed
    at /Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2789085
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2861044
    at async ka.get (/Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2871213)
    at async /Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2860979
    at async ca (/Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2860946)
    at async /Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2864782
    at async Object.getContext (/Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2864738)
    at async oi (/Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2727430)
    at async /Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2874871 {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/user',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'VS Code GitHub Actions (0.27.0) octokit-rest.js/19.0.7 octokit-core.js/4.1.0 Node.js/20.16.0 (darwin; arm64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound e] }
  }
}
[Error - 10:04:44 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: fetch failed
  Code: -32603
```

I tried following the advice in https://github.com/github/vscode-github-actions/issues/282, but that did not help. However, after disabling GitHub Actions, restarting Extensions and enabling GitHub Actions, I got this similar error in the OUTPUT (only differences posted):

```
Failure to retrieve username:  Ls [HttpError]: fetch failed
    .
    .
    at async _n (/Users/user/.vscode/extensions/github.vscode-github-actions-0.27.0/dist/server-node.js:2:2763253) {
    .
    .
}
[Error - 10:10:37 AM] Unhandled error while validating: fetch failed
```

**Additional context**
macOS Sonoma 14.7
The GitHub Actions activity bar icon works fine

**Comment by DrStrangepork** [comment]
I also tried logging out of my Account and logging back in. That made no difference: same errors, GitHub Actions activity bar icon continues to work fine

**Comment by pevnyk** [comment]
Any updates on this?
I have the exact same issue.

GitHub Actions v. 0.27.1

VsCode
Version: 1.98.2 (user setup)
Commit: ddc367ed5c8936efe395cffeec279b04ffd7db78
Date: 2025-03-12T13:32:45.399Z
Electron: 34.2.0
ElectronBuildId: 11161602
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by kj8000** [comment]
Facing same issue
