### ISSUE TITLE
Unable to refresh, could not reach GitHub API

### ISSUE THREAD

**Issue by alexanderilyin** [github/vscode-github-actions#435]
Type: <b>Bug</b>

Can not get list of GH Actions for current branch. PR in question:

- https://github.com/partcad/partcad/pull/228

```
Activating GitHub Actions extension...
...initialized
Error getting GitHub context
fetch failed
HttpError: fetch failed
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1369793
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1451022
    at Object.get (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450749)
    at Lt (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450941)
    at hs.refresh (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1617420)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1629917
    at cw.h (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
Error getting GitHub context
fetch failed
HttpError: fetch failed
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1369793
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1451022
    at Object.get (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450749)
    at Lt (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450941)
    at hs.refresh (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1617420)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1629917
    at cw.h (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
Error getting GitHub context
fetch failed
HttpError: fetch failed
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1369793
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1451022
    at Object.get (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450749)
    at Lt (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450941)
    at hs.refresh (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1617420)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1629917
    at cw.h (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
Error getting GitHub context
fetch failed
HttpError: fetch failed
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1369793
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:454:9)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1451022
    at Object.get (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450749)
    at Lt (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450941)
    at hs.refresh (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1617420)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1629917
    at cw.h (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
Error getting GitHub context
fetch failed
HttpError: fetch failed
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1369793
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:454:9)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1451022
    at Object.get (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450749)
    at Lt (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450941)
    at hs.refresh (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1617420)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1629917
    at cw.h (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
Error getting GitHub context
fetch failed
HttpError: fetch failed
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1369793
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1451022
    at Object.get (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450749)
    at Lt (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1450941)
    at hs.refresh (/home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1617420)
    at /home/vscode/.vscode-server/extensions/github.vscode-github-actions-0.27.0/dist/extension-node.js:2:1629917
    at cw.h (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
```

Extension version: 0.27.0
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|79.91GB (51.84GB free)|
|Process Argv|--crash-reporter-id 828c2b46-e47b-405a-9312-09a86750d998|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: PartCAD Dev Container @ desktop-linux|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 0)|
|Memory (System)|39.13GB (35.18GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by alvicsam** [comment]
Could be related to https://github.com/orgs/community/discussions/147375

**Comment by alexanderilyin** [comment]
Maybe, it does feel like I only started to notice it after I started to use secret for SSH key.
